# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 296
  rpc: https://testnet.hashio.io/api
  start_block: 0
  contracts:
  - name: ParimutuelPredictionMarket
    address:
    - 0x53F25235E70380605EA794dA768d9662AB72aD52
    handler: ./src/EventHandlers.js
    events:
    - event: BetPlaced(uint256 indexed questionId, address indexed user, uint256 indexed outcomeIndex, uint256 amount)
    - event: MarketResolved(uint256 indexed questionId, uint256 indexed winningOutcome)
    - event: QuestionAdded(uint256 indexed questionId, string question, string[] outcomeNames, uint256 endTime)
    - event: WinningsClaimed(uint256 indexed questionId, address indexed user, uint256 amount)
unordered_multichain_mode: true
preload_handlers: true
